### ISSUE TITLE
When all movable player pieces are gone... (vs AI)

### ISSUE THREAD

**Issue by NCK5Koen** [Avans/Stratego#5]
When AI has only bombs and the flag, it can't make a move. The problem is that the player can't make a move either. The player can only make a move after refreshing the page.

Tested on my API

**Comment by Linksonder** [comment]
Leuke bug. Deze ga ik niet meer oppakken aangezien we volgend jaar doorschuiven naar een nieuwe opdracht en dan komt deze API te vervallen.
