### ISSUE TITLE
valid post to /games/{gameId}/moves returns 500 error

### ISSUE THREAD

**Issue by grtrapma** [Avans/Stratego#6]
valid post to /games/{gameId}/moves returns 
"{
    "message": "Unknown modifier: $pushAll"
}"

Google says this is a mongoose error. 
![afbeelding](https://user-images.githubusercontent.com/33327688/43509211-4737adbe-9572-11e8-8650-c5d87d78d217.png)

**Comment by grtrapma** [comment]
https://stackoverflow.com/questions/48607918/mongoerror-unknown-modifier-pushall-in-node-js, could it be that your DB provider updated your mongo instance?

**Comment by grtrapma** [comment]
![afbeelding](https://user-images.githubusercontent.com/33327688/43539714-eb8b6614-95c5-11e8-90b4-43351e7927cb.png)
also on your stratego app

**Comment by Linksonder** [comment]
Bedankt voor het melden van dit issue, en extra bedankt voor de pull request! Ik heb de pull geaccepteerd en de nieuwe versie is released.  Fixed via #7
